// Generated by https://quicktype.io

export interface ISub {
  id?: string;
  name: string;
  logo: string;
  price: number;
  expiration?: string;
  email?: string;
  password?: string;
  colorId: number;
  color: Color;
  user?: User;
}

export interface Color {
  id: number;
  name: string;
}

export interface User {
  id: string;
  email: string;
  fullName: string;
  avatar: string;
  isActive: boolean;
  roles: string[];
}
